const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const rows=fs.readdirSync(__dirname+'/../data').filter(p=>p.endsWith('.json')).flatMap(p=>JSON.parse(fs.readFileSync(__dirname+'/../data/'+p,'utf8')).map(row=>({...row,imageAssetId:null,imageUrl:''})));
const mock='window.__rows='+JSON.stringify(rows)+';window.fetch=async(path,opts={})=>{if(opts.method==="PUT"){const id=decodeURIComponent(path.split("/").pop()),body=JSON.parse(opts.body);window.__rows=window.__rows.map(row=>row.id===id?{...body.value,id}:row)}return new Response(JSON.stringify(path==="/api/session"?{canWrite:true}:window.__rows),{headers:{"Content-Type":"application/json"}})};window.__csv=[];const oldURL=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{if(blob.type==="text/csv")blob.text().then(text=>window.__csv.push(text));return oldURL(blob)};';await page.setContent('<script>'+mock+'</script>'+fs.readFileSync(__dirname+'/../app/index.html','utf8'));await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===156);
assert.equal(await page.locator('thead th:visible').count(),13);assert.equal(await page.locator('[data-spec]').count(),156*7);assert.ok(await page.locator('#rows tr').evaluateAll(rows=>rows.every(row=>row.cells.length===13)));
const field=(sku,key)=>page.locator('tr[data-id="'+sku+'"]').locator('[data-spec="'+key+'"] .spec-value');const rank=async(sku,key)=>field(sku,key).evaluate(e=>e.classList.contains('high')?'high':e.classList.contains('low')?'low':'');
assert.equal(await field('sf-e905smart','speedResistanceLevels').innerText(),'8 resistance levels');assert.equal(await rank('sf-e905smart','speedResistanceLevels'),'low');assert.equal(await rank('sf-e324005','speedResistanceLevels'),'high');assert.equal(await rank('sf-e324028','speedResistanceLevels'),'');assert.equal(await field('sf-e324028','speedResistanceLevels').innerText(),'18 speed levels');assert.equal(await rank('sf-e322004','inclineStrideMotion'),'low');assert.equal(await rank('sf-e902s','inclineStrideMotion'),'high');assert.equal(await rank('sf-e320048','inclineStrideMotion'),'');assert.equal(await field('sf-rw1205smart','maxUserWeightLb').innerText(),'220 lb');assert.equal(await field('sf-rw522017blk','driveResistanceSystem').innerText(),'Water + Magnetic');
assert.equal(await field('sf-e905smart','keyDimensions').innerText(),'40.7"L × 26.4"W × 59.8"H');assert.equal(await field('sf-e905smart','workoutAreaWidthIn').innerText(),'-');assert.equal(await field('sf-rw1205smart','workoutAreaLengthIn').innerText(),'-');
const untouched=rows.find(i=>!i.productSpecs&&!i.treadmillSpecs);assert.ok(await page.locator('tr[data-id="'+untouched.id+'"] [data-spec]').evaluateAll(cells=>cells.every(c=>c.innerText==='-'&&!c.querySelector('.high,.low'))));
await page.locator('#exportBtn').click();await page.waitForFunction(()=>window.__csv.length===1);assert.match(await page.evaluate(()=>window.__csv[0]),/Workout Area Width \(in\)/);assert.match(await page.evaluate(()=>window.__csv[0]),/8 resistance levels/);
for(const [category,count] of [['Ellipticals',18],['Rowers',13],['Indoor Bikes',26]]){await page.locator('[data-cat="'+category+'"]').click();assert.equal(await page.locator('#rows tr').count(),count);assert.equal(await page.locator('thead th:visible').count(),13);assert.equal(await page.locator('[data-spec]').count(),count*7);}
await page.locator('[data-cat="Ellipticals"]').click();assert.equal(await rank('sf-e905smart','speedResistanceLevels'),'low');await page.locator('#q').fill('e905');assert.equal(await rank('sf-e905smart','speedResistanceLevels'),'low');await page.locator('#qclear').click();
await page.locator('#compareToggle').check();await page.locator('[data-compare="sf-e905smart"]').check();await page.locator('[data-compare="sf-e324005"]').check();await page.locator('#compareConfirm').click();assert.equal(await page.locator('#rows tr').count(),2);assert.equal(await rank('sf-e905smart','speedResistanceLevels'),'low');await page.locator('[data-cat="Rowers"]').click();assert.equal(await page.locator('#compareToggle').isChecked(),false);assert.equal(await page.locator('#rows tr').count(),13);
await page.locator('#bulkBtn').click();assert.equal(await page.locator('[data-spec]').count(),91);await page.locator('#bulkDone').click();await page.locator('[data-edit="sf-rw1205smart"]').click();await page.locator('#f-name').fill('Rower review title');await page.locator('#saveBtn').click();await page.waitForFunction(()=>window.__rows.find(i=>i.id==='sf-rw1205smart').name==='Rower review title');assert.equal(await field('sf-rw1205smart','maxUserWeightLb').innerText(),'220 lb');
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#compareToggle').check();await page.locator('[data-compare="sf-rw1205smart"]').check();await page.locator('#compareConfirm').click();assert.equal(await page.locator('#rows tr').count(),1);assert.equal(await page.locator('[data-spec]').count(),7);await page.locator('#compareToggle').uncheck();assert.equal(await page.locator('#rows tr').count(),13);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: uniform headers/cells/CSV across 156 products, elliptical and rower workbook values, neutral missing data and pad dimensions, category-based stable numeric tiers, separate speed/resistance levels, comparison reset, edit/bulk preservation and mobile layout.');})().catch(e=>{console.error(e);process.exit(1)});
