const {DatabaseSync}=require('node:sqlite');const fs=require('fs'),assert=require('assert');const {pathToFileURL}=require('url');
(async()=>{global.APP_HTML='<html>catalog</html>';global.APP_CATALOG=fs.readdirSync(__dirname+'/../data').filter(p=>p.endsWith('.json')).flatMap(p=>JSON.parse(fs.readFileSync(__dirname+'/../data/'+p,'utf8')).map(row=>({...row,imageAssetId:null,imageUrl:'/api/catalog-images/'+p.slice(0,-5)+'/'+row.id+'.jpg'})));const {default:worker}=await import(pathToFileURL(__dirname+'/../server/worker.js'));const sql=new DatabaseSync(':memory:');for(const name of fs.readdirSync(__dirname+'/../drizzle').filter(n=>n.endsWith('.sql')))sql.exec(fs.readFileSync(__dirname+'/../drizzle/'+name,'utf8'));
function prepare(query){let values=[];const stmt=sql.prepare(query);return{bind(...v){values=v;return this},async first(){return stmt.get(...values)||null},async all(){return {results:stmt.all(...values)}},async run(){const r=stmt.run(...values);return {meta:{changes:Number(r.changes)}}}}}
const pictures=new Map();const env={DB:{prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}},BUCKET:{async put(id,body,options){pictures.set(id,{body,...options})},async get(id){return pictures.get(id)}}};
async function request(path,method='GET',body=null,signed=true){const headers={};if(signed)headers['oai-authenticated-user-id']='test-owner';if(body!==null)headers['Content-Type']='application/json';return worker.fetch(new Request('https://app.test'+path,{method,headers,body:body===null?null:JSON.stringify(body)}),env)}
let response=await request('/api/items');const seed=await response.json();assert.equal(seed.length,156);assert.equal(seed.filter(i=>i.category==='Treadmills').length,23);const cross=seed.find(i=>i.id==='sf-rbe420049-bikes');assert.ok(cross);assert.equal((await request('/api/items/'+cross.id,'PUT',{value:cross,createOnly:false})).status,200);const treadmill=seed.find(i=>i.sku==='SF-T724081');assert.equal(treadmill.treadmillSpecs.workoutAreaWidthIn,18.1);const edited={...treadmill,name:'Pace custom title'};delete edited.treadmillSpecs;assert.equal((await request('/api/items/'+treadmill.id,'PUT',{value:edited,createOnly:false})).status,200);const persisted=(await (await request('/api/items')).json()).find(i=>i.id===treadmill.id);assert.equal(persisted.name,'Pace custom title');assert.equal(persisted.treadmillSpecs.workoutAreaWidthIn,18.1);// Simulate upgrading an existing saved catalog with custom edits and without the new metadata.
sql.exec("DELETE FROM catalog_meta WHERE key = 'master-elliptical-rower-specs-v1'");sql.exec("UPDATE items SET data = json_remove(data, '$.productSpecs') WHERE json_extract(data, '$.category') IN ('Ellipticals','Rowers')");sql.exec("UPDATE items SET data = json_set(data, '$.name', 'Custom elliptical title') WHERE id = 'sf-e905smart'");
const upgraded=await (await request('/api/items')).json();assert.equal(upgraded.filter(i=>i.productSpecs).length,31);const elliptical=upgraded.find(i=>i.id==='sf-e905smart');assert.equal(elliptical.name,'Custom elliptical title');assert.equal(elliptical.productSpecs.resistanceLevels,8);assert.equal(elliptical.productSpecs.strideLengthIn,11);assert.equal(elliptical.productSpecs.workoutAreaWidthIn,null);assert.equal(upgraded.find(i=>i.id==='sf-rw1205smart').productSpecs.maxUserWeightLb,220);
const saveElliptical={...elliptical,name:'Edited elliptical'};delete saveElliptical.productSpecs;assert.equal((await request('/api/items/'+elliptical.id,'PUT',{value:saveElliptical,createOnly:false})).status,200);assert.equal((await (await request('/api/items')).json()).find(i=>i.id===elliptical.id).productSpecs.resistanceLevels,8);
const item={...seed[0],sku:'SF-T900',name:'Integration Test',imageAssetId:null};response=await request('/api/items/sf-t900','PUT',{value:item,createOnly:true},false);assert.equal(response.status,403);response=await request('/api/items/sf-t900','PUT',{value:item,createOnly:true});assert.equal(response.status,200);response=await request('/api/items/sf-t900','PUT',{value:item,createOnly:true});assert.equal(response.status,409);response=await request('/api/items/sf-t900','PUT',{value:{...item,price:-5},createOnly:false});assert.equal(response.status,400);response=await request('/api/items/move','POST',{oldId:'sf-t900',newId:seed[1].id,value:{...item,sku:seed[1].sku}});assert.equal(response.status,409);assert.ok((await (await request('/api/items')).json()).some(i=>i.id==='sf-t900'));response=await request('/api/items/move','POST',{oldId:'sf-t900',newId:'sf-t901',value:{...item,sku:'SF-T901'}});assert.equal(response.status,200);assert.ok((await (await request('/api/items')).json()).some(i=>i.id==='sf-t901'));
const picture=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jKfkAAAAASUVORK5CYII=','base64');response=await worker.fetch(new Request('https://app.test/api/assets',{method:'POST',headers:{'oai-authenticated-user-id':'test-owner','Content-Type':'image/png'},body:picture}),env);assert.equal(response.status,201);const asset=await response.json();response=await request('/api/assets/'+asset.id);assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'image/png');
response=await worker.fetch(new Request('https://app.test/api/items/sf-t901',{method:'DELETE',headers:{'oai-authenticated-user-id':'test-owner',origin:'https://evil.test'}}),env);assert.equal(response.status,403);for(const i of await (await request('/api/items')).json())await request('/api/items/'+i.id,'DELETE');assert.equal((await (await request('/api/items')).json()).length,0);console.log('PASS: database migrations, 156-record catalog initialization, persisted CRUD, server authorization, validation, unique SKU collision and atomic rename, image storage, origin checks, and no reseeding after deletion.');sql.close()})().catch(e=>{console.error(e);process.exit(1)});
