const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const rows=fs.readdirSync(__dirname+'/../data').filter(p=>p.endsWith('.json')).flatMap(p=>JSON.parse(fs.readFileSync(__dirname+'/../data/'+p,'utf8')).map(row=>({...row,imageAssetId:null,imageUrl:''})));
const mock='window.__rows='+JSON.stringify(rows)+';window.fetch=async(path,opts={})=>{if(opts.method==="PUT"){const id=decodeURIComponent(path.split("/").pop()),body=JSON.parse(opts.body);window.__rows=window.__rows.map(row=>row.id===id?{...body.value,id}:row)}return new Response(JSON.stringify(path==="/api/session"?{canWrite:true}:window.__rows),{headers:{"Content-Type":"application/json"}})};window.URLSearchParams=class{get(key){return key==="category"?"Treadmills":null}};window.__csv=[];const oldURL=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{if(blob.type==="text/csv")blob.text().then(text=>window.__csv.push(text));return oldURL(blob)};';await page.setContent('<script>'+mock+'</script>'+fs.readFileSync(__dirname+'/../app/index.html','utf8'));await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===23);assert.equal(await page.locator('thead th:visible').count(),13);assert.equal(await page.locator('[data-spec]').count(),161);assert.equal(await page.locator('#specLegend').isVisible(),true);
assert.equal(await page.locator('.spec-review,#tierSort,#tierDirection,#viewSpecs').count(),0);
await page.locator('#compareToggle').check();assert.equal(await page.locator('thead th:visible').count(),14);assert.equal(await page.locator('#compareConfirm').isEnabled(),false);
assert.equal(await page.locator('thead th').nth(1).getAttribute('id'),'compareHead');
await page.locator('[data-compare="sf-t724081"]').check();await page.locator('#q').fill('1407');await page.locator('[data-compare="sf-t1407smart"]').check();
await page.locator('#compareConfirm').click();assert.equal(await page.locator('#rows tr').count(),2);assert.deepEqual((await page.locator('#rows tr').evaluateAll(rows=>rows.map(r=>r.dataset.id))).sort(),['sf-t1407smart','sf-t724081']);
await page.locator('.tablebox').evaluate(el=>el.scrollLeft=900);
const fixed=await page.locator('#rows tr').first().evaluate(row=>{const box=document.querySelector('.tablebox').getBoundingClientRect(),sku=row.querySelector('.c-sku').getBoundingClientRect(),img=row.querySelector('.c-img').getBoundingClientRect(),price=row.querySelector('.c-price').getBoundingClientRect();return {left:sku.left-box.left,imageGap:img.left-sku.right,priceGap:price.left-img.right};});assert.ok(Math.abs(fixed.left)<3);assert.ok(Math.abs(fixed.imageGap)<3);assert.ok(Math.abs(fixed.priceGap)<3);
await page.locator('#compareToggle').uncheck();assert.equal(await page.locator('#rows tr').count(),1);assert.equal(await page.locator('[data-compare]').count(),0);assert.equal(await page.locator('#compareConfirm').isVisible(),false);await page.locator('#qclear').click();assert.equal(await page.locator('#rows tr').count(),23);
await page.locator('#compareToggle').check();await page.locator('[data-compare="sf-t724081"]').check();await page.locator('[data-compare="sf-t1407smart"]').check();await page.locator('#compareConfirm').click();await page.locator('[data-compare="sf-t1407smart"]').uncheck();assert.equal(await page.locator('#rows tr').count(),2);await page.locator('#compareConfirm').click();assert.equal(await page.locator('#rows tr').count(),1);await page.locator('#compareToggle').uncheck();assert.equal(await page.locator('#rows tr').count(),23);
// Tier ordering uses the same independent ranks as the displayed colors.
for(const key of ['driveResistanceSystem','speedResistanceLevels','inclineStrideMotion','maxUserWeightLb','workoutAreaWidthIn','workoutAreaLengthIn']){
 const ranks=()=>page.locator('[data-spec="'+key+'"] .spec-value').evaluateAll(els=>els.map(el=>el.classList.contains('high')?0:el.classList.contains('low')?2:1));
 await page.locator('th[data-key="tier:'+key+'"] .header-label button').click();let order=await ranks();assert.deepEqual(order,[...order].sort((a,b)=>a-b));
 await page.locator('th[data-key="tier:'+key+'"] .header-label button').click();order=await ranks();assert.deepEqual(order,[...order].sort((a,b)=>b-a));
}

await page.locator('.tablebox').evaluate(el=>{el.scrollTop=500;el.scrollLeft=600});
assert.ok(await page.locator('th[data-key="tier:driveResistanceSystem"]').evaluate(el=>Math.abs(el.getBoundingClientRect().top-document.querySelector('.tablebox').getBoundingClientRect().top)<3));
await page.locator('.tablebox').evaluate(el=>{el.scrollTop=0;el.scrollLeft=0});
const field=(sku,key)=>page.locator('tr[data-id="'+sku+'"]').locator('[data-spec="'+key+'"] .spec-value');assert.equal(await field('sf-t724081','workoutAreaWidthIn').innerText(),'18.1 in');assert.equal(await field('sf-t724081','workoutAreaLengthIn').innerText(),'52.4 in');assert.equal(await field('sf-t724081','keyDimensions').innerText(),'52.4" × 18.1"');assert.equal(await field('sf-t725067','workoutAreaWidthIn').innerText(),'-');assert.equal(await page.locator('[data-spec="workoutAreaWidthIn"] .unknown').count(),4);assert.equal(await page.locator('[data-spec="inclineStrideMotion"] .unknown').count(),2);
assert.equal(await field('sf-x7200smart','driveResistanceSystem').evaluate(e=>e.classList.contains('high')),true);assert.equal(await field('sf-x7200smart','speedResistanceLevels').evaluate(e=>e.classList.contains('low')),true);assert.equal(await field('sf-t1407smart','driveResistanceSystem').evaluate(e=>e.classList.contains('low')||e.classList.contains('high')),false);assert.equal(await field('sf-t1407smart','workoutAreaWidthIn').evaluate(e=>e.classList.contains('low')),true);assert.equal(await field('sf-t1407smart','maxUserWeightLb').evaluate(e=>e.classList.contains('high')),true);
await page.locator('#q').fill('x7200');assert.equal(await page.locator('#rows tr').count(),1);assert.equal(await field('sf-x7200smart','driveResistanceSystem').evaluate(e=>e.classList.contains('high')),true);await page.locator('#qclear').click();await page.locator('#bulkBtn').click();assert.equal(await page.locator('[data-spec]').count(),161);await page.locator('#bulkDone').click();await page.locator('[data-edit="sf-t724081"]').click();await page.locator('#f-name').fill('Pace 500 review');await page.locator('#saveBtn').click();await page.waitForFunction(()=>window.__rows.find(i=>i.id==='sf-t724081').name==='Pace 500 review');assert.equal(await field('sf-t724081','workoutAreaWidthIn').innerText(),'18.1 in');await page.locator('#exportBtn').click();await page.waitForFunction(()=>window.__csv.length===1);assert.match(await page.evaluate(()=>window.__csv[0]),/Workout Area Width \(in\)/);assert.match(await page.evaluate(()=>window.__csv[0]),/"18.1","52.4"/);
await page.locator('[data-cat="Ellipticals"]').click();assert.equal(await page.locator('#rows tr').count(),18);assert.equal(await page.locator('[data-spec]').count(),126);assert.equal(await page.locator('thead th:visible').count(),13);assert.equal(await page.locator('#specLegend').isVisible(),true);await page.locator('[data-cat="Treadmills"]').click();assert.equal(await page.locator('[data-spec]').count(),161);
const contrast=async cls=>page.locator('.spec-value.'+cls).first().evaluate(el=>{const c=getComputedStyle(el),lum=s=>{const rgb=s.match(/\d+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722};const a=lum(c.color),b=lum(c.backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)});assert.ok(await contrast('high')>=4.5);assert.ok(await contrast('low')>=4.5);await page.screenshot({path:'/workspace/work/treadmill-desktop.png'});await page.emulateMedia({colorScheme:'dark'});assert.ok(await contrast('high')>=4.5);assert.ok(await contrast('low')>=4.5);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#compareToggle').check();await page.locator('[data-compare="sf-t724081"]').check();await page.locator('[data-compare="sf-t1407smart"]').check();await page.locator('#compareConfirm').click();assert.equal(await page.locator('#rows tr').count(),2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#compareToggle').uncheck();assert.equal(await page.locator('#rows tr').count(),23);await page.locator('#q').fill('724081');assert.equal(await page.locator('[data-spec]').count(),7);assert.ok(await page.locator('[data-spec]').evaluateAll(cells=>Math.min(...cells.map(cell=>cell.getBoundingClientRect().width)))>290);await page.screenshot({path:'/workspace/work/treadmill-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: comparison selection/confirmation/reset on desktop and mobile, three frozen columns, sticky headers and tier ordering, all 7 columns for 23 treadmills, workbook values and missing specs, independent tiers, stable search colors, bulk display, spec persistence after edit, CSV, unaffected other categories, light/dark contrast, direct treadmill view and mobile layout.');})().catch(e=>{console.error(e);process.exit(1)});
