const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
function validate(v){if(!v||typeof v!=='object')throw fail('Invalid item');for(const k of ['name','sku','category'])if(typeof v[k]!=='string'||!v[k].trim())throw fail(k+' is required');if(v.sku.length>100||/[\/\x00-\x1f]/.test(v.sku))throw fail('SKU contains invalid characters');if(v.name.length>1000||v.category.length>150)throw fail('Item text is too long');if(v.price!==null&&(!Number.isFinite(v.price)||v.price<0))throw fail('Price must be a non-negative number');let url;try{url=new URL(v.url)}catch{throw fail('Use a valid HTTPS link')}if(url.protocol!=='https:')throw fail('Use a valid HTTPS link');if(v.imageAssetId&&!/^[a-f0-9-]+\.(png|jpg|webp)$/.test(v.imageAssetId))throw fail('Invalid picture ID');return {treadmillSpecs:keepSpecs(v.treadmillSpecs),name:v.name.trim(),sku:v.sku.trim().toUpperCase(),category:v.category.trim(),price:v.price,priceChecked:!!v.priceChecked,url:url.href,imageAssetId:v.imageAssetId||null,imageUrl:typeof v.imageUrl==='string'&&/^\/api\/catalog-images\/[a-z0-9-]+\/[a-z0-9-]+\.jpg$/.test(v.imageUrl)?v.imageUrl:'',createdAt:v.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
function keepSpecs(value){if(!value||typeof value!=='object')return null;const result={};for(const field of ['driveResistanceSystem','speedResistanceLevels','inclineStrideMotion','keyDimensions','source','dimensionOrder','portfolioCategory'])result[field]=typeof value[field]==='string'?value[field].slice(0,1000):null;for(const field of ['maxUserWeightLb','workoutAreaWidthIn','workoutAreaLengthIn','advertisedMotorHp','maxSpeedMph'])result[field]=typeof value[field]==='number'&&Number.isFinite(value[field])&&value[field]>=0?value[field]:null;return result}
async function hydrateSpecs(db){const key='master-treadmill-specs-v1';if(await db.prepare('SELECT value FROM catalog_meta WHERE key = ?').bind(key).first())return;const {results}=await db.prepare('SELECT id,data FROM items').all();const source=new Map(APP_CATALOG.filter(i=>i.category==='Treadmills'&&i.treadmillSpecs).map(i=>[i.sku,i.treadmillSpecs]));const updates=results.map(row=>{const item=JSON.parse(row.data);const specs=item.category==='Treadmills'?source.get(item.sku):null;return specs?db.prepare("UPDATE items SET data = json_set(data, '$.treadmillSpecs', json(?)) WHERE id = ?").bind(JSON.stringify(specs),row.id):null}).filter(Boolean);await db.batch([...updates,db.prepare('INSERT OR IGNORE INTO catalog_meta (key,value) VALUES (?,?)').bind(key,'imported')])}
const dbFor=env=>{if(!env.DB)throw fail('Catalog database is unavailable',503);return env.DB};
async function initialize(db){const marker='github-catalog-18d9844';const flag=await db.prepare('SELECT value FROM catalog_meta WHERE key = ?').bind(marker).first();if(flag)return;const inserts=APP_CATALOG.map(i=>db.prepare('INSERT OR IGNORE INTO items (id,data) VALUES (?,?)').bind(i.id,JSON.stringify(i)));const cleanup=['DEMO-T001','DEMO-T002','DEMO-T003'].map(sku=>db.prepare('DELETE FROM items WHERE id = ? AND json_extract(data, \'$.name\') LIKE \'Sample %\'').bind(sku.toLowerCase()));await db.batch([...inserts,...cleanup,db.prepare('INSERT OR IGNORE INTO catalog_meta (key,value) VALUES (?,?)').bind(marker,'imported')])}

export default {async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/'&&request.method==='GET')return new Response(APP_HTML,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'none'"}});
if(!url.pathname.startsWith('/api/'))return new Response('Not found',{status:404});
// The owner-private Sites access boundary protects all routes. Writes also require a signed-in user.
const user=request.headers.get('oai-authenticated-user-id');if(request.method!=='GET'){if(!user)throw fail('Sign in to edit the catalog',403);const origin=request.headers.get('origin');if(origin&&origin!==url.origin)throw fail('Invalid request origin',403)}
if(url.pathname==='/api/session')return json({canWrite:!!user});
if(url.pathname==='/api/assets'&&request.method==='POST'){if(!env.BUCKET)throw fail('Picture storage is unavailable',503);const type=request.headers.get('Content-Type');const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[type];if(!ext)throw fail('Choose a JPEG, PNG or WebP image');const bytes=await request.arrayBuffer();if(bytes.byteLength>10*1024*1024)throw fail('Picture must be smaller than 10 MB',413);if(bytes.byteLength<12)throw fail('Invalid picture');const a=new Uint8Array(bytes);if((ext==='png'&&!(a[0]===137&&a[1]===80&&a[2]===78&&a[3]===71))||(ext==='jpg'&&!(a[0]===255&&a[1]===216))||(ext==='webp'&&!(String.fromCharCode(...a.slice(0,4))==='RIFF'&&String.fromCharCode(...a.slice(8,12))==='WEBP')))throw fail('File contents do not match the picture type');const id=crypto.randomUUID()+'.'+ext;await env.BUCKET.put(id,bytes,{httpMetadata:{contentType:type}});return json({id},201)}
if(url.pathname.startsWith('/api/assets/')&&request.method==='GET'){const key=decodeURIComponent(url.pathname.slice(12));if(!/^[a-f0-9-]+\.(png|jpg|webp)$/.test(key))throw fail('Invalid picture ID');if(!env.BUCKET)throw fail('Picture storage is unavailable',503);const obj=await env.BUCKET.get(key);if(!obj)return new Response('Picture not found',{status:404});return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType||'application/octet-stream','X-Content-Type-Options':'nosniff','Cache-Control':'private,max-age=300'}})}
if(url.pathname.startsWith('/api/catalog-images/')&&request.method==='GET'){const path=url.pathname.slice('/api/catalog-images/'.length);if(!APP_CATALOG.some(i=>i.imageUrl==='/api/catalog-images/'+path))throw fail('Picture not found',404);const key='catalog/'+path;let object=env.BUCKET?await env.BUCKET.get(key):null;if(object)return new Response(object.body,{headers:{'Content-Type':'image/jpeg','Cache-Control':'private,max-age=86400','X-Content-Type-Options':'nosniff'}});const response=await fetch('https://raw.githubusercontent.com/steveh00898/SS/18d984479d00ac6ae0ed88356d1bb4b4cd216544/data/images/'+path);if(!response.ok)throw fail('Picture unavailable',502);const bytes=await response.arrayBuffer();if(env.BUCKET)await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:'image/jpeg'}});return new Response(bytes,{headers:{'Content-Type':'image/jpeg','Cache-Control':'private,max-age=86400','X-Content-Type-Options':'nosniff'}})}
const db=dbFor(env);
if(url.pathname==='/api/items'&&request.method==='GET'){await initialize(db);await hydrateSpecs(db);const {results}=await db.prepare('SELECT id,data FROM items ORDER BY id').all();return json(results.map(i=>({...JSON.parse(i.data),id:i.id})))}
if(url.pathname==='/api/items/move'&&request.method==='POST'){const body=await request.json(),value=validate(body.value),id=value.sku.toLowerCase();if(id!==body.newId)throw fail('SKU and ID do not match');const update=await db.prepare('UPDATE items SET id = ?, data = ? WHERE id = ?').bind(id,JSON.stringify(value),body.oldId).run();if(!update.meta.changes)throw fail('Item no longer exists',404);return json({id})}
if(url.pathname.startsWith('/api/items/')){const id=decodeURIComponent(url.pathname.slice(11));if(request.method==='DELETE'){await db.prepare('DELETE FROM items WHERE id = ?').bind(id).run();return json({deleted:true})}if(request.method==='PUT'){const body=await request.json(),value=validate(body.value);const canonical=value.sku.toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'');const existing=await db.prepare('SELECT data FROM items WHERE id = ?').bind(id).first();if(existing&&body.value.treadmillSpecs===undefined)value.treadmillSpecs=JSON.parse(existing.data).treadmillSpecs||null;if(id!==canonical&&(!existing||JSON.parse(existing.data).sku!==value.sku))throw fail('SKU and ID do not match');if(body.createOnly){await db.prepare('INSERT INTO items (id,data) VALUES (?,?)').bind(id,JSON.stringify(value)).run()}else{const result=await db.prepare('UPDATE items SET data = ? WHERE id = ?').bind(JSON.stringify(value),id).run();if(!result.meta.changes)throw fail('Item no longer exists',404)}return json({id})}}
return new Response('Not found',{status:404})}catch(e){console.error('Catalog request failed',url.pathname,e.message);return json({error:/UNIQUE constraint/.test(e.message)?'This SKU is already in the catalog.':e.status?e.message:'The catalog could not complete this request. Please try again.'},/UNIQUE constraint/.test(e.message)?409:e.status||500)}}};
